version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    ignore:
      # Ikke bump major på Node-avhengigheter, ønsker å manuelt bytte til ny major-versjon når den er i LTS-stadiet
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    groups:
      aksel:
        applies-to: version-updates
        patterns:
          - "@navikt/aksel*"
          - "@navikt/ds*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      react-router:
        applies-to: version-updates
        patterns:
          - "@react-router*"
          - "react-router"
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
      testcontainers:
        patterns:
          - "@testcontainers/postgresql"
          - 'testcontainers'

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    ignore:
      # Ikke bump major på Node-avhengigheter, ønsker å manuelt bytte til ny major-versjon når den er i LTS-stadiet
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      # Ikke bump major på Node-avhengigheter, ønsker å manuelt bytte til ny major-versjon når den er i LTS-stadiet
      - dependency-name: "europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
