minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@navikt/*'
  - '@nais/*'
allowBuilds:
  cpu-features: true
  esbuild: true
  lefthook: true
  protobufjs: true
  ssh2: true
overrides:
  '@types/node': ^24.13.3
  uuid@<14.0.2: '>=14.0.2 <15.0.0'
