name: Build and Deploy

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-and-typecheck:
    name: Lint and typecheck
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Lint and typecheck
        run: pnpm run check

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Unit tests
        run: pnpm test

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Integration tests
        run: pnpm run test:integration

  build:
    if: github.ref == 'refs/heads/main'
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: nais/docker-build-push@f8bc7437f7549c2b08197152d781b98f8727a08a # v0
        id: docker-push
        with:
          team: pensjon-revisjon
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          build_args: GITHUB_SHA=${{ github.sha }}

  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy to prod-gcp
    needs: [lint-and-typecheck, unit-tests, integration-tests, build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # pinned
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod.yaml
          VAR: image=${{ needs.build.outputs.image }}
